typography_spectrum: 0.3198166307993233
color:
  brandColors:
    - '#141218'
    - '#FFFFFF'
    - '#77797B'
    - '#E19A26'
    - '#FE0029'
  brandStrength: 0.3580810446292162
  lightness: 0.23438590043224394
  saturation: 0.8797711771912873
  rhythmicContrast: 0.15065512317232788
github: true
layout_spectrum: 0.7361833588220179
author:
  name: MJ
  email: host@itsamans.world
  url: 'http://itsamans.world'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/855f188c-b1c8-4306-803b-dfd96088a21a.png
name: It's a MAN's World
url: 'http://itsamans.world/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: What is a man
    id: c533441e-bce8-4eb4-a4f5-53b1c3522dad
    type: content
  - name: Hobbies and Pursuits
    id: a19f7c6d-a528-4c2f-9366-578e43b05784
    type: content
  - name: Not Every Man Is Married With Kids
    id: 5d30d091-ca53-4364-9c90-f48add0fa411
    type: content
  - name: The Eye Within The Eye
    id: 6e63d16a-385a-435d-9017-383087d12857
    type: content
  - name: Business Opportunities and Advice
    url: 'http://business.itsamans.world'
    type: external
  - name: Geeks and Gadgets
    url: 'http://geeks.itsamans.world'
    type: external
title: It's a MAN's World
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/b4990229-41ac-4a03-ae05-b932ad57472c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/b4990229-41ac-4a03-ae05-b932ad57472c.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Where Manhood Is Celebrated, Not Debated'
